sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: gt1303190518
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10


  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: arthur-sky-takeout
    region: cn-beijing
    file-path: dishImages/